version: '2'

### Services
services:
### Web Server Container ##################################
    web:
        image: lobsterk/docker-nginx-php-fpm7.0
        container_name: web
        restart: always
        links:
           - "mysql"
        ports:
            - "$WEB_PORTS"
        volumes:
           - $PROJECT_PATH:/var/www/html
           - $DOCKRIXDIR/nginx/default.conf:/etc/nginx/conf.d/default.conf
           - $DOCKRIXDIR/nginx/nginx.conf:/etc/nginx/nginx.conf
           - $DOCKRIXDIR/php-fpm/php.ini:/etc/php/7.0/fpm/php.ini
           - $DOCKRIXDIR/php-fpm/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
        networks:
          default:
            ipv4_address: $WEB_IP
## MySQL Container
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        ports:
            - "$MYSQL_PORTS"
        volumes:
              - ./mysql/:/docker-entrypoint-initdb.d/
              - $DOCKRIXDIR/mysql/:/etc/mysql/conf.d/
        environment:
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        networks:
            default:
              ipv4_address: $MYSQL_IP
    adminer:
            image: adminer
            ports:
                - "$ADMINER_PORTS"
### Network
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
              - subnet: $SUBNET
                gateway: $GATEWAY